
application: icrashrep
version: 1-1-005
runtime: python
api_version: 1

handlers:

- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico
  mime_type: image/vnd.microsoft.icon

- url: /styles
  static_dir: styles
  
- url: /images
  static_dir: images
  
- url: /static
  static_dir: static
  
- url: /
  static_files: static/index.html  
  upload: static/index.html
  
- url: /\.*\/*Packages.bz2
  static_files: debs/Packages.bz2
  upload: debs/Packages.bz2
  mime_type: application/octet-stream
  
- url: /\.*\/*([^\/]*\.deb)
  static_files: debs/\1
  upload: debs/(.*\.deb)
  mime_type: application/octet-stream

- url: /test
  script: service.py

- url: /up
  script: service.py

- url: /report
  script: service.py

- url: /manage/(.*)
  script: manage.py
  login: admin 

