application: icrashrep
version: 1
runtime: python
api_version: 1

handlers:

- url: /\.*\/*Packages.bz2
  static_files: debs/Packages.bz2
  upload: debs/Packages.bz2
  
- url: /\.*\/*([^\/]*\.deb)
  static_files: debs/\1
  upload: debs/(.*\.deb)

- url: /
  script: service.py

- url: /up
  script: service.py

- url: /report
  script: service.py
